# Generated by Django 3.0.7 on 2020-06-10 19:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('points', '0002_allprojects_newsletterrecipients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('project_name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, upload_to='projects/')),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(blank=True, related_name='liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.IntegerField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('content', models.IntegerField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('usability', models.IntegerField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('jury', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='profile/')),
                ('bio', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AllProjects',
        ),
        migrations.DeleteModel(
            name='AllUsers',
        ),
    ]
