# Generated by Django 3.0.7 on 2020-06-11 01:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_auto_20200611_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='points.Project'),
            preserve_default=False,
        ),
    ]
